---
title: Dressipi
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog_categories:
    title: Categories
    output: true
  clients:
    title: Clients
    output: false
  downloads:
    title: Downloads
    output: true
  jobs:
    title: Jobs
    output: false
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  integrations:
    title: integrations
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    image: 
    author: 
    button:
      title: 
      url: 
    description: 
- scope:
    path: ''
    type: blog_categories
  values:
    permalink: "/blog/categories/:title/"
    layout: category
- scope:
    path: ''
    type: blog_tags
  values:
    permalink: "/blog/tags/:title/"
    layout: tag
- scope:
    path: ''
    type: resources
  values:
    layout: resource
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    image: 
    twitter: 
- scope:
    path: ''
    type: downloads
  values:
    permalink: "/downloads/:title/"
    resource: 
    image: 
    form:
      title: Download Now
      button: Download >
      file: 
    testimonial:
      body: 
      logo: 
      author:
        name: 
        job-title: 
        company: 
        image: 
      action: Download Now
    layout: download
- scope:
    path: ''
    type: clients
  values:
    logo: 
    link: 
- scope:
    path: ''
    type: pages
  values:
    navigation: 
    header:
      title: 
      body: 
      button:
        copy: 
        url: 
      hero-image: 
    is-landing-page: false
    downloads: 
    layout: page
    description: 
- scope:
    path: ''
    type: jobs
  values:
    is-open: true
seo:
  title: SEO Dressipi.com
description: Personalising the Entire Customer Experience
url: https://dressipi.com
form-demo:
  title: Make a Step-Change in Personalization
  button: BOOK A DEMO >
  email_cc: 
  redirect: "/thanks"
company:
  name: Stylemania Ltd.
  address:
    street: 85 Great Portland Street
    city: London W1W 7LT
twitter:
  username: dressipi
social:
  links:
  - name: Twitter
    link: https://www.twitter.com/dressipi
  - name: Instagram
    link: https://www.instagram.com/dressipi
  - name: LinkedIn
    link: https://www.linkedin.com/company/dressipi
  - name: YouTube
    link: https://www.youtube.com/channel/UCek0mxAxImkuiSgiWmq3bMA
date_format: "%-d %B %Y"
per_page: 10
permalink: pretty
exclude:
- Gemfile.lock
- README*
- ".gitignore"
- prettierignore
- node_modules
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
john-lewis:
  garment-112:
    fit: Tailored
    style: Single Breasted Blazer
    length: Standard
    pattern: Plain
    brand: Reiss
    color: Pistachio
